### ISSUE TITLE
Windows frozen after workspace switch

### ISSUE THREAD

**Issue by dtolnay** [paperwm/PaperWM#108]
After pulling in 65e009815ad5b1f76a1acc8a395e3bbbd60f430c, I find that sometimes after activating the switch-to-workspace-N keybinding I land in the intended workspace and I see the right windows in that workspace, but the content of those windows is frozen. I can make clicks in the window or press keys in the window but the effect of those interactions is not drawn. If I drag on the left or right edge of a frozen window, it unfreezes and I see the result of all the clicks and keypresses that happened while it was frozen.

For now I have gone back to e8a9eea8e94914d3f4ce9fe5ceac0035bed8d99e which does not exhibit this behavior. I have not tried bisecting yet because I don't know which of the commits in https://github.com/paperwm/PaperWM/compare/e8a9eea8e94914d3f4ce9fe5ceac0035bed8d99e...65e009815ad5b1f76a1acc8a395e3bbbd60f430c are intended to be working states, but I can try if that would be helpful. Filing the issue in case you recognize something obvious that would cause this.

**Comment by hedning** [comment]
Hmm, yeah that sounds like https://github.com/paperwm/PaperWM/issues/73

The topbar is probably shown and then hidden again, updating the workarea and pushing the window down causing a resize which is then fixed immediately.

We need to add something like this:
https://github.com/mlutfy/hidetopbar/blob/8434af7e42032d42fcf9bbb209e7b00fb37b86d7/panelVisibilityManager.js#L44-L48

@olejorgenb has a fix incoming :)

**Comment by dtolnay** [comment]
Thanks! I will report back if it happens again.

**Comment by goodwillcoding** [comment]
@hedning @olejorgenb ... this fix broke other extensions that my guess connect signals to the panel bar. For example Dash-to-Dock is now overlapped by the top bar.

![image](https://user-images.githubusercontent.com/582074/57181775-f21bf880-6e4c-11e9-9698-e9c0b108b1b5.png)

**Comment by hedning** [comment]
Right, dash to dock will position itself using the available workarea. https://github.com/paperwm/PaperWM/commit/86283c5deaed3c926395314987aa6e094b450d58 made the topbar not affect the workarea, fixing the freeze, but causing the dock to extend to the top.

We'll either need proper per workspace workarea, https://github.com/paperwm/PaperWM/issues/109, or manage to fix the freeze problem some other way.

**Comment by olejorgenb** [comment]
They  probably position based on the workarea.  See #109

We could disable the top bar struts only when at least one workspace is configured to hide the topbar - hoping the people that want the topbar hidden doesn't overlap with users of extensions relying on the y position of the workarea.

**Comment by olejorgenb** [comment]
@goodwillcoding e1f6a980ef16dbc1f28f442de5c1c9efca3fb424 should fix the dash-to-dock issue

@dtolnay Let us know if the fix reintroduced the freeze issue. I've tested on 3.28.

**Comment by goodwillcoding** [comment]
@olejorgenb : the revert fixes the issue on the main desktop. it still occurs in overview though, which potentially is a less problematic issue but though I'd mention it anyway

**Comment by olejorgenb** [comment]
@goodwillcoding  Just be sure: it's when the overview is opened from a workspace with _hidden_ topbar you refer to, right? (if I open the overview from a workspace with _visible_ topbar it works as expected here)

Workarea updates seems to be deferred while a "modal" is open so I don't think there's anything we can do.  (3.28 X11 - I think it might've changed in 3.3x)
